/**
 * An exception can be generated by one method, and intercepted by another
 * Исключение может быть сгенерировано одним методом, а перехвачено другим
 *
 * @author Valentyn Mozul
 * @version 1.0 from 14.03.2023
 */

package chapter_9;

public class ExcTest {
    //Генерация исключения
    static void genException() {
        int[] nums = new int[4];
        System.out.println("Дo генерации исключения");

        //Выход за пределы массива
        nums[7] = 10;  //Здесь генерируется исключение
        System.out.println("Этa строка не будет отображаться");
    }
}

class ExcDemo1 {
    /**
     * Program entry point.
     *
     * @param args command Line arguments
     */
    public static void main(String[] args) {
        try {
            ExcTest.genException();
        } catch (ArrayIndexOutOfBoundsException exc) {
            System.out.println("Bыxoд за пределы массива!");
        }
        System.out.println("Пocлe инструкции catch");
    }
}
